[project]
name = "freq-count"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fire>=0.7.1",
    "loguru>=0.7.3",
    "spacy>=3.8.7",
    "tqdm>=0.0.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.11",
]
